"""init

Revision ID: 37a2c153721d
Revises: 
Create Date: 2021-05-20 14:32:58.194178

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '37a2c153721d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('api_id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(), nullable=False),
                    sa.Column('rus_title', sa.String(), nullable=True),
                    sa.Column('alias', sa.String(), nullable=True),
                    sa.Column('flag', sa.String(), nullable=True),
                    sa.Column('group', sa.String(), nullable=True),
                    sa.Column('active', sa.Boolean(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('user',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('api_id', sa.Integer(), nullable=False),
                    sa.Column('chat_stage', sa.Integer(), nullable=True),
                    sa.Column('chat_stage_payload', sa.String(), nullable=True),
                    sa.Column('username', sa.String(), nullable=True),
                    sa.Column('fulll_name', sa.String(), nullable=True),
                    sa.Column('created', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_user_chat_id'), 'user', ['chat_id'], unique=False)
    op.create_table('match',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('api_id', sa.Integer(), nullable=False),
                    sa.Column('datetime', sa.DateTime(), nullable=False),
                    sa.Column('stage', sa.Integer(), nullable=False),
                    sa.Column('group', sa.String(), nullable=False),
                    sa.Column('stadium', sa.String(), nullable=False),
                    sa.Column('team_home_id', sa.Integer(), nullable=True),
                    sa.Column('team_away_id', sa.Integer(), nullable=True),
                    sa.Column('home_goals_90', sa.Integer(), nullable=True),
                    sa.Column('away_goals_90', sa.Integer(), nullable=True),
                    sa.Column('home_goals_total', sa.Integer(), nullable=True),
                    sa.Column('away_goals_total', sa.Integer(), nullable=True),
                    sa.Column('status', sa.Integer(), nullable=True),
                    sa.Column('processed', sa.Boolean(), nullable=True),
                    sa.Column('updated', sa.DateTime(), nullable=True),
                    sa.Column('created', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['team_away_id'], ['team.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['team_home_id'], ['team.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_match_group'), 'match', ['group'], unique=False)
    op.create_index(op.f('ix_match_team_away_id'), 'match', ['team_away_id'], unique=False)
    op.create_index(op.f('ix_match_team_home_id'), 'match', ['team_home_id'], unique=False)
    op.create_table('prediction',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('match_id', sa.Integer(), nullable=True),
                    sa.Column('home_goals', sa.Integer(), nullable=True),
                    sa.Column('away_goals', sa.Integer(), nullable=True),
                    sa.Column('points', sa.Integer(), nullable=True),
                    sa.Column('created', sa.DateTime(), nullable=True),
                    sa.Column('updated', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_prediction_match_id'), 'prediction', ['match_id'], unique=False)
    op.create_index(op.f('ix_prediction_user_id'), 'prediction', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prediction_user_id'), table_name='prediction')
    op.drop_index(op.f('ix_prediction_match_id'), table_name='prediction')
    op.drop_table('prediction')
    op.drop_index(op.f('ix_match_team_home_id'), table_name='match')
    op.drop_index(op.f('ix_match_team_away_id'), table_name='match')
    op.drop_index(op.f('ix_match_group'), table_name='match')
    op.drop_table('match')
    op.drop_index(op.f('ix_user_chat_id'), table_name='user')
    op.drop_table('user')
    op.drop_table('team')
    # ### end Alembic commands ###
