"""user notifications

Revision ID: 6886ec40a90b
Revises: 76507b6c782f
Create Date: 2021-06-10 10:04:03.932365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6886ec40a90b'
down_revision = '76507b6c782f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('notifications_on', sa.Boolean(), nullable=True))
    op.drop_column('userlog', 'notifications_on')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userlog', sa.Column('notifications_on', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('user', 'notifications_on')
    # ### end Alembic commands ###
