"""add userlog

Revision ID: 76507b6c782f
Revises: 37a2c153721d
Create Date: 2021-05-21 17:41:19.323104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76507b6c782f'
down_revision = '37a2c153721d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userlog',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('request', sa.String(), nullable=True),
    sa.Column('response', sa.String(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_userlog_user_id'), 'userlog', ['user_id'], unique=False)
    op.alter_column('match', 'stadium',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('match', 'stadium',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_userlog_user_id'), table_name='userlog')
    op.drop_table('userlog')
    # ### end Alembic commands ###
