"""match penalty goals

Revision ID: e7f8b82d596e
Revises: 6886ec40a90b
Create Date: 2021-06-24 10:02:29.043855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7f8b82d596e'
down_revision = '6886ec40a90b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('home_goals_pen', sa.Integer(), nullable=True))
    op.add_column('match', sa.Column('away_goals_pen', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match', 'away_goals_pen')
    op.drop_column('match', 'home_goals_pen')
    # ### end Alembic commands ###
